// TechFix Pro — Flutter widget test entry point.
//
// The default counter-increment test generated by `flutter create` does not
// apply to this app.  Widget integration tests live in widget_smoke_test.dart.
//
// This file is kept to satisfy the test runner's expectation of a
// test/widget_test.dart file without any false-positive failures.

import 'package:flutter_test/flutter_test.dart';

void main() {
  test('placeholder — see widget_smoke_test.dart for real tests', () {
    expect(1 + 1, equals(2));
  });
}
